#!/usr/bin/env ruby
# frozen_string_literal: true

require "yaml"
require "fileutils"
require "date"

ROOT = File.expand_path("..", __dir__)
DATA_DIR = File.join(ROOT, "_data")
OUTPUT = File.join(__dir__, "cv-data.tex")

def load_data(name)
  YAML.load_file(File.join(DATA_DIR, name), aliases: true)
end

def tex(value)
  value.to_s.gsub("\\", "\\textbackslash{}")
       .gsub(/([#$%&_{}])/) { "\\#{Regexp.last_match(1)}" }
       .gsub("~", "\\textasciitilde{}")
       .gsub("^", "\\textasciicircum{}")
end

def tex_url(value)
  value.to_s.gsub(/([#$%&_{}])/) { "\\#{Regexp.last_match(1)}" }
end

def link(url, label)
  "\\href{#{tex_url(url)}}{#{tex(label)}}"
end

def entry(title, institution, period, detail)
  "\\CVEntry{#{tex(title)}}{#{tex(institution)}}{#{tex(period)}}{#{tex(detail)}}"
end

cv = load_data("cv.yml")
research = load_data("research.yml")
talks = load_data("talks.yml")
teaching = load_data("teaching.yml")
miscellany = load_data("miscellany.yml")

publications = research.fetch("publications", []).map do |publication|
  citation = tex(publication.fetch("citation"))
  doi = publication["doi"]
  doi ? "\\item #{citation} [#{link(doi, publication.fetch("doi_label", "link"))}]" : "\\item #{citation}"
end

preprints = research.fetch("preprints", []).map do |preprint|
  citation = tex(preprint.fetch("citation"))
  doi = preprint["doi"]
  doi ? "\\item #{citation} [#{link(doi, preprint.fetch("doi_label", "link"))}]" : "\\item #{citation}"
end

scientific_contributions = talks.flat_map do |year_group|
  year_group.fetch("talks", []).select { |talk| talk["category"] == "scientific_contribution" }
end

def talk_entry(talk)
    event = talk.fetch("event")
    event = link(talk["event_url"], event) if talk["event_url"]
    "\\CVTalk{#{tex(talk.fetch("title"))}}{#{event}}{#{tex(talk.fetch("date"))}}"
end

contributions_by_type = scientific_contributions.group_by { |talk| talk.fetch("contribution_type") }

teaching_groups = teaching.map do |year_group|
  courses = year_group.fetch("courses", []).map do |course|
    name = course.fetch("name")
    translation = course["translation"]
    name = "#{name} (#{translation})" if translation
    degree = course.fetch("degree")
    degree = link(course["degree_url"], degree) if course["degree_url"]
    "\\CVCourse{#{tex(name)}}{#{degree}}"
  end

  { year: year_group["year"], courses: courses }
end

lines = []
lines << "% Generated by build_cv.rb. Do not edit directly."
lines << "\\newcommand{\\CVName}{#{tex(cv.dig("personal", "name"))}}"
lines << "\\newcommand{\\CVTitle}{#{tex(cv.dig("personal", "title"))}}"
lines << "\\newcommand{\\CVLastUpdated}{#{Date.today.strftime("%d %B %Y")}}"
lines << "\\newcommand{\\CVPersonalDetails}{%"
lines << "  \\textbf{Location:} #{tex(cv.dig("personal", "location"))}\\\\[2pt]"
lines << "  \\textbf{Nationality:} #{tex(cv.dig("personal", "nationality"))}\\\\[2pt]"
lines << "  \\textbf{Date of birth:} #{tex(cv.dig("personal", "date_of_birth"))}\\\\[2pt]"
lines << "  \\textbf{Email:} \\texttt{#{tex(cv.dig("personal", "email"))}}\\\\[2pt]"
lines << "  \\textbf{Personal webpage:} #{link(cv.dig("personal", "website"), cv.dig("personal", "website"))}\\\\[2pt]"
lines << "  \\textbf{ORCID:} #{link(cv.dig("personal", "orcid"), cv.dig("personal", "orcid"))}"
lines << "}"
lines << "\\newcommand{\\CVBio}{#{tex(cv.fetch("bio"))}}"
lines << "\\newcommand{\\CVEducation}{%"
cv.fetch("education").each { |item| lines << entry(item["degree"], item["institution"], item["period"], item["detail"]) }
lines << "}"
lines << "\\newcommand{\\CVResearchExperience}{%"
cv.fetch("research_experience").each { |item| lines << entry(item["role"], item["institution"], item["period"], item["detail"]) }
lines << "}"
research_stays = Array(cv["research_stays"])
lines << "\\newif\\ifCVHasResearchStays"
lines << (research_stays.empty? ? "\\CVHasResearchStaysfalse" : "\\CVHasResearchStaystrue")
lines << "\\newcommand{\\CVResearchStays}{%"
research_stays.each { |item| lines << entry(item["role"], item["institution"], item["period"], item["detail"]) }
lines << "}"
other_scientific_meetings = Array(cv["other_scientific_meetings_attended"])
lines << "\\newif\\ifCVHasOtherScientificMeetings"
lines << (other_scientific_meetings.empty? ? "\\CVHasOtherScientificMeetingsfalse" : "\\CVHasOtherScientificMeetingstrue")
lines << "\\newcommand{\\CVOtherScientificMeetings}{%"
other_scientific_meetings.each do |item|
  lines << "\\CVMeeting{#{tex(item.fetch("event"))}}{#{tex(item["institution"])} }{#{tex(item.fetch("period"))}}{#{tex(item["detail"])}}"
end
lines << "}"
lines << "\\newcommand{\\CVAwards}{%"
cv.fetch("awards").each { |item| lines << entry(item["name"], item["organization"], item["year"], item["detail"]) }
lines << "}"
lines << "\\newcommand{\\CVPublications}{\\begin{enumerate}[leftmargin=*,label={[\\arabic*]},itemsep=2pt,topsep=0pt]#{publications.join}\\end{enumerate}}"
lines << "\\newcommand{\\CVPreprints}{\\begin{enumerate}[leftmargin=*,label={[\\arabic*]},itemsep=2pt,topsep=0pt]#{preprints.join}\\end{enumerate}}"
lines << "\\newcommand{\\CVInvitedConferenceTalks}{%"
lines.concat(contributions_by_type.fetch("invited_conference_talk", []).map { |talk| talk_entry(talk) })
lines << "}"
lines << "\\newcommand{\\CVContributedConferenceTalks}{%"
lines.concat(contributions_by_type.fetch("contributed_conference_talk", []).map { |talk| talk_entry(talk) })
lines << "}"
lines << "\\newcommand{\\CVSeminars}{%"
lines.concat(contributions_by_type.fetch("seminar", []).map { |talk| talk_entry(talk) })
lines << "}"
lines << "\\newcommand{\\CVPosters}{%"
lines.concat(contributions_by_type.fetch("poster", []).map { |talk| talk_entry(talk) })
lines << "}"
lines << "\\newcommand{\\CVTeaching}{%"
teaching_groups.each do |group|
  if group[:year]
    lines << "\\CVTeachingYear{#{tex(group[:year])}}{%"
    lines.concat(group[:courses])
    lines << "}"
  else
    lines.concat(group[:courses])
  end
end
lines << "}"
outreach_and_volunteering = Array(cv["outreach_and_volunteering"])
lines << "\\newif\\ifCVHasOutreachAndVolunteering"
lines << (outreach_and_volunteering.empty? ? "\\CVHasOutreachAndVolunteeringfalse" : "\\CVHasOutreachAndVolunteeringtrue")
lines << "\\newcommand{\\CVOutreachAndVolunteering}{%"
outreach_and_volunteering.each { |item| lines << "\\CVCompactEntry{#{tex(item["activity"])}}{}{#{tex(item["period"])}}{#{tex(item["detail"])}}" }
lines << "}"
academic_activities = Array(cv["academic_activities_organized"])
lines << "\\newif\\ifCVHasAcademicActivitiesOrganized"
lines << (academic_activities.empty? ? "\\CVHasAcademicActivitiesOrganizedfalse" : "\\CVHasAcademicActivitiesOrganizedtrue")
lines << "\\newcommand{\\CVAcademicActivitiesOrganized}{%"
academic_activities.each do |item|
  detail = item["detail_tex"] || tex(item["detail"])
  lines << "\\CVCompactEntry{#{tex(item["activity"])}}{}{#{tex(item["period"])}}{#{detail}}"
end
lines << "}"
lines << "\\newcommand{\\CVLanguages}{#{cv.fetch("languages").map { |item| tex(item) }.join("; ")}}"

File.write(OUTPUT, lines.join("\n") + "\n")
puts "Generated #{OUTPUT}"